#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum unicorne_layers {
    _BASE,
    _SYMB,
    _NAV,
    _SETT
};

enum unicorne_keycodes {
    Base = SAFE_RANGE,
    SYMB,
    NAV,
    SETT
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

	[_BASE] = LAYOUT_split_3x6_3(KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T,         KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
                             KC_TAB, KC_A, KC_S, KC_D, KC_F, KC_G,         KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_ENT,
                             KC_LALT, KC_Z, KC_X, KC_C, KC_V, KC_B,        KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_ESC,
                                             NAV, KC_LCTL, KC_LSFT,        KC_SPC, SYMB, KC_LGUI),

    [_SYMB] = LAYOUT_split_3x6_3(KC_GRV,  KC_1,  KC_2,  KC_3,  KC_4,  KC_5,              KC_6,  KC_7,  KC_8,  KC_9,  KC_0,  KC_DEL,
                             KC_TRNS, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC,      KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_QUOT,
                             KC_TRNS, KC_NO, KC_NO, KC_SLSH, KC_EQL, KC_PLUS,        KC_MINS, KC_UNDS, KC_LBRC, KC_RBRC, KC_BSLS, KC_TRNS,
                                                     SETT, KC_LCTL, KC_LSFT,         KC_SPC, KC_TRNS, KC_LGUI),

    [_NAV] = LAYOUT_split_3x6_3(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5,             KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC,
                             KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6,         KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_TRNS,
                             KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
                                               KC_TRNS, KC_LCTL, KC_LSFT,      KC_SPC, SETT, KC_LGUI),

    [_SETT] = LAYOUT_split_3x6_3(QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLU,     RGB_VAI, RGB_HUI, RGB_SAI, RGB_MOD, RGB_TOG, KC_NO,
                             EE_CLR, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLD,      RGB_VAD, RGB_HUD, RGB_SAD, RGB_RMOD, CK_TOGG, KC_NO,
                             KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE,       KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
                                              KC_TRNS, KC_TRNS, KC_TRNS,       KC_TRNS, KC_TRNS, KC_TRNS)
};



RGB_MATRIX_EFFECT(ALPHAS_MODS)

rgb_matrix_sethsv(0x00, 0x80, 0x80)
rgb_matrix_set_speed(0x99)



#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




